package ch.r7studio.studiomanager.pojo;
// Generated 28.04.2013 03:04:57 by Hibernate Tools 3.2.1.GA



/**
 * BusinessObject generated by hbm2java
 */
public class Businessobject implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String value;

    public Businessobject() {
    }

	
    public Businessobject(String value) {
        this.value = value;
    }
    public Businessobject(String name, String description, String value) {
       this.name = name;
       this.description = description;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


