package ch.r7studio.studiomanager.pojo;
// Generated 28.04.2013 03:04:57 by Hibernate Tools 3.2.1.GA



/**
 * Channel generated by hbm2java
 */
public class Channel  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String trigger;
     private String action;

    public Channel() {
    }

    public Channel(String name, String description, String trigger, String action) {
       this.name = name;
       this.description = description;
       this.trigger = trigger;
       this.action = action;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTrigger() {
        return this.trigger;
    }
    
    public void setTrigger(String trigger) {
        this.trigger = trigger;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


