package ch.r7studio.studiomanager.pojo;
// Generated 28.04.2013 03:04:57 by Hibernate Tools 3.2.1.GA



/**
 * SnomvisionButton generated by hbm2java
 */
public class Snomvisionbutton implements java.io.Serializable {


     private int address;
     private short value;

    public Snomvisionbutton() {
    }

    public Snomvisionbutton(int address, short value) {
       this.address = address;
       this.value = value;
    }
   
    public int getAddress() {
        return this.address;
    }
    
    public void setAddress(int address) {
        this.address = address;
    }
    public short getValue() {
        return this.value;
    }
    
    public void setValue(short value) {
        this.value = value;
    }




}


