package ch.r7studio.studiomanager;
// Generated 28.04.2013 03:03:19 by Hibernate Tools 3.2.1.GA



/**
 * SnomvisionButton generated by hbm2java
 */
public class SnomvisionButton  implements java.io.Serializable {


     private int address;
     private short value;

    public SnomvisionButton() {
    }

    public SnomvisionButton(int address, short value) {
       this.address = address;
       this.value = value;
    }
   
    public int getAddress() {
        return this.address;
    }
    
    public void setAddress(int address) {
        this.address = address;
    }
    public short getValue() {
        return this.value;
    }
    
    public void setValue(short value) {
        this.value = value;
    }




}


