package com.r7studio.ioserver;
// Generated 19.04.2013 20:14:23 by Hibernate Tools 3.2.1.GA



/**
 * Channel generated by hbm2java
 */
public class Channel  implements java.io.Serializable {


     private short address;
     private short value;
     private Short onMode;
     private Short onColor;
     private Short offMode;
     private Short offColor;
     private String oid;
     private String i2c;

    public Channel() {
    }

	
    public Channel(short address, short value) {
        this.address = address;
        this.value = value;
    }
    public Channel(short address, short value, Short onMode, Short onColor, Short offMode, Short offColor, String oid, String i2c) {
       this.address = address;
       this.value = value;
       this.onMode = onMode;
       this.onColor = onColor;
       this.offMode = offMode;
       this.offColor = offColor;
       this.oid = oid;
       this.i2c = i2c;
    }
   
    public short getAddress() {
        return this.address;
    }
    
    public void setAddress(short address) {
        this.address = address;
    }
    public short getValue() {
        return this.value;
    }
    
    public void setValue(short value) {
        this.value = value;
    }
    public Short getOnMode() {
        return this.onMode;
    }
    
    public void setOnMode(Short onMode) {
        this.onMode = onMode;
    }
    public Short getOnColor() {
        return this.onColor;
    }
    
    public void setOnColor(Short onColor) {
        this.onColor = onColor;
    }
    public Short getOffMode() {
        return this.offMode;
    }
    
    public void setOffMode(Short offMode) {
        this.offMode = offMode;
    }
    public Short getOffColor() {
        return this.offColor;
    }
    
    public void setOffColor(Short offColor) {
        this.offColor = offColor;
    }
    public String getOid() {
        return this.oid;
    }
    
    public void setOid(String oid) {
        this.oid = oid;
    }
    public String getI2c() {
        return this.i2c;
    }
    
    public void setI2c(String i2c) {
        this.i2c = i2c;
    }




}


