package com.r7studio.ioserver;
// Generated 09.04.2013 00:39:28 by Hibernate Tools 3.2.1.GA



/**
 * Ioboard generated by hbm2java
 */
public class Ioboard  implements java.io.Serializable {


     private String ip;
     private String type;
     private Integer temp;

    public Ioboard() {
    }

	
    public Ioboard(String ip, String type) {
        this.ip = ip;
        this.type = type;
    }
    public Ioboard(String ip, String type, Integer temp) {
       this.ip = ip;
       this.type = type;
       this.temp = temp;
    }
   
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getTemp() {
        return this.temp;
    }
    
    public void setTemp(Integer temp) {
        this.temp = temp;
    }




}


