package com.r7studio.ioserver;
// Generated 19.04.2013 20:14:23 by Hibernate Tools 3.2.1.GA



/**
 * Modclient generated by hbm2java
 */
public class Modclient  implements java.io.Serializable {


     private String ip;

    public Modclient() {
    }

    public Modclient(String ip) {
       this.ip = ip;
    }
   
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


