package com.r7studio.ioserver;
// Generated 09.04.2013 00:39:28 by Hibernate Tools 3.2.1.GA



/**
 * Snomclient generated by hbm2java
 */
public class Snomclient  implements java.io.Serializable {


     private String ip;

    public Snomclient() {
    }

    public Snomclient(String ip) {
       this.ip = ip;
    }
   
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


